In [1]:
import numpy as np

n = 3 
position = np.zeros([n, n]) # ([row, col])
print position

for i in range(0,n):
    for j in range(0,n):
       arr[i][j]= input("enter:")
print position


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
enter:0
enter:1
enter:2
enter:3
enter:4
enter:5
enter:6
enter:7
enter:8
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
