In [1]:
import numpy as np

n = 3 
position = np.zeros([n, n]) # ([row, col])
print position

for i in range(0,n):
    for j in range(0,n):
       arr[i][j]= input("enter:")
print position

"""如附檔，只要改成是裡面的n，就可以做成一個n*n的[類似矩陣的東西，
因為python沒有矩陣qaq]，然後依序輸入你要輸入的[電荷大小]，就可以
以較圖像化的方式，呈現電荷在平面上的分布；也可以以輸入index[i][j]
的方式指定某電荷的位置。到時候要做電場分布，可考慮以此作為使用者輸
入。(若覺得有更方便或更好的想法請跟我說~~)"""

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
enter:0
enter:1
enter:2
enter:3
enter:4
enter:5
enter:6
enter:7
enter:8
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
